/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result codes from the native library */
export const enum ResultCode {
  Success = 0,
  ProposalError = 1,
  ProverError = 2,
  SignerError = 3,
  SigningError = 4,
  ExtractorError = 5,
  IoError = 6,
  ParseError = 7,
  VerificationError = 8,
  InvalidIndex = 9,
  InvalidSignature = 10,
  CombineError = 11
}
/** Payment request with address, amount, and optional metadata */
export interface Payment {
  /** Zcash address (unified, transparent, or shielded) */
  address: string
  /** Amount in zatoshis (as string to handle BigInt from JavaScript) */
  amount: string
  /** Optional memo for shielded outputs */
  memo?: string
  /** Optional label */
  label?: string
  /** Optional message */
  message?: string
}
/** Transparent UTXO input to spend */
export interface TransparentInput {
  /** Compressed public key (33 bytes) */
  pubkey: Buffer
  /** Transaction ID (32 bytes) */
  txid: Buffer
  /** Output index */
  vout: number
  /** Amount in zatoshis (as string to handle BigInt from JavaScript) */
  amount: string
  /** P2PKH script pubkey */
  scriptPubKey: Buffer
}
/** Transparent transaction output (for change verification) */
export interface TransparentOutput {
  /** P2PKH script pubkey (raw bytes, no CompactSize prefix) */
  scriptPubKey: Buffer
  /** Amount in zatoshis (as string to handle BigInt from JavaScript) */
  value: string
}
/** Create a PCZT from transparent inputs and transaction request */
export declare function proposeTransaction(inputs: Array<TransparentInput>, request: TransactionRequest): Pczt
/** Create a PCZT with explicit change handling */
export declare function proposeTransactionWithChange(inputs: Array<TransparentInput>, request: TransactionRequest, changeAddress: string): Pczt
/** Add Orchard proofs to the PCZT */
export declare function proveTransaction(pczt: Pczt): Pczt
/** Verify the PCZT before signing */
export declare function verifyBeforeSigning(pczt: Pczt, request: TransactionRequest, expectedChange: Array<TransparentOutput>): void
/** Get signature hash for a transparent input */
export declare function getSighash(pczt: Pczt, index: number): Buffer
/** Append an external signature to the PCZT */
export declare function appendSignature(pczt: Pczt, index: number, signature: Buffer): Pczt
/** Combine multiple PCZTs into one (not implemented in C FFI) */
export declare function combine(pczts: Array<Pczt>): Pczt
/** Finalize the PCZT and extract transaction bytes */
export declare function finalizeAndExtract(pczt: Pczt): Buffer
/** Serialize PCZT to bytes */
export declare function serialize(pczt: Pczt): Buffer
/** Parse PCZT from bytes */
export declare function parse(bytes: Buffer): Pczt
/** Transaction request containing multiple payments */
export declare class TransactionRequest {
  /** Create a new transaction request with a specific target block height */
  static withTargetHeight(payments: Array<Payment>, targetHeight: number): TransactionRequest
  /** Create a new transaction request from payment array */
  constructor(payments: Array<Payment>)
  /** Set the target block height for consensus branch ID selection */
  setTargetHeight(height: number): void
  /** Free the native resources */
  free(): void
}
export type PCZT = Pczt
/** Partially Constructed Zcash Transaction (PCZT) */
export declare class Pczt {
  /**
   * Free the native resources
   * Note: Most operations consume the PCZT
   */
  free(): void
}
